name: 'Node 12 Template Action'
description: 'Get started with Node actions'
author: 'GitHub'
inputs:
  repo-token:
    description: 'The GITHUB_TOKEN secret'
runs:
  using: 'node12'
  main: 'index.js'
